StudyJunction/StudyJunction.Web/Areas/Admin/Controllers/CoursesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StudyJunction.Core.Services.Contracts;
using StudyJunction.Infrastructure.Constants;

namespace StudyJunction.Web.Areas.Admin.Controllers
{
    [Area(RolesConstants.Admin)]
    [Authorize(Roles = RolesConstants.Admin)]
    public class CoursesController : Controller
    {
        private readonly ICourseService courseService;

        public CoursesController(ICourseService courseService)
        {
            this.courseService = courseService;
        }

        [HttpGet]
        public async Task<IActionResult> GetAllForApproval()
        {
            var coursesForApproval = await courseService.GetAllNotApproved();

            return View("ForApproval", coursesForApproval);
        }

        [HttpPost]
        public async Task<IActionResult> Approve(string courseId)
        {
            try
            {
                await courseService.ApproveCourseAsync(new Guid(courseId));

                return RedirectToAction("GetAllForApproval", "Courses", new { area = RolesConstants.Admin });
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", new { area = RolesConstants.Admin });
            }
        }

    }
}

StudyJunction/StudyJunction.Web/Areas/God/Controllers/CoursesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StudyJunction.Core.Services.Contracts;
using StudyJunction.Infrastructure.Constants;

namespace StudyJunction.Web.Areas.God.Controllers
{
    [Area(RolesConstants.God)]
    [Authorize(Roles = RolesConstants.God)]
    public class CoursesController : Controller
    {
		private readonly ICourseService courseService;

		public CoursesController(ICourseService courseService)
        {
			this.courseService = courseService;
		}

        [HttpGet]
        public async Task<IActionResult> GetAllForApproval()
        {
            var coursesForApproval = await courseService.GetAllNotApproved();

            return View("ForApproval", coursesForApproval);
        }

        [HttpPost]
        public async Task<IActionResult> Approve(string courseId) 
        {
            try
            {
                await courseService.ApproveCourseAsync(new Guid(courseId));

                return RedirectToAction("GetAllForApproval", "Courses", new {area = RolesConstants.God});
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", new { area = RolesConstants.God });
			}
        }

    }
}

StudyJunction/StudyJunction.Web/Areas/Student/Controllers/CoursesController.cs
using AutoMapper;
using CloudinaryDotNet;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using StudyJunction.Core.ExternalApis;
using StudyJunction.Core.RequestDTOs.Course;
using StudyJunction.Core.ResponseDTOs;
using StudyJunction.Core.Services.Contracts;
using StudyJunction.Core.ViewModels.Courses;
using StudyJunction.Infrastructure.Constants;
using StudyJunction.Infrastructure.Data.Models;
using StudyJunction.Infrastructure.Exceptions;
using System.Collections.Specialized;

namespace StudyJunction.Web.Areas.Student.Controllers
{
    [Area(RolesConstants.Student)]
    [Authorize(Roles = RolesConstants.Student)]
    public class CoursesController : Controller
    {
        private readonly ICourseService courseService;
        private readonly IUserService userService;
        private readonly IMapper mapper;
        private readonly ICategoryService categoryService;
        private readonly CloudinaryService cloudinaryService;
        public CoursesController(ICourseService _courseService, IUserService _userService, IMapper _mapper, ICategoryService _categoryService,
            CloudinaryService _cloudinaryService)
        {
            courseService = _courseService;
            userService = _userService;
            mapper = _mapper;
            categoryService = _categoryService;
            cloudinaryService = _cloudinaryService;
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var viewModel = new CreateCourseViewModel();

            var parentChildCategoreis = await this.categoryService.GetAllParentChildCategoriesForSelectingCategory();

            viewModel.ParentChildCategories = parentChildCategoreis.ParentChildCategories;

            return View("Create", viewModel);
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateCourseViewModel viewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                { 
                    return View(viewModel);
                }

                string username = HttpContext.Session.GetString("user");

                var course = mapper.Map<AddCourseRequestDto>(viewModel);

                _ = await courseService.Create(course, username);

                var routeValues = new RouteValueDictionary
                {
                    { "controller", "Courses" },
                    { "action", "Details" },
                    { "title", viewModel.Title }
                };

                var redirectResult = new RedirectToActionResult("Details", "Courses", routeValues);

                return redirectResult;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return RedirectToAction("Create");
            }
        }

        [HttpGet]
        public async Task<IActionResult> Index(string searchbar, [FromQuery] string? category)
        {
            CourseViewModel viewModel = new CourseViewModel()
            {
                Service = cloudinaryService,
                Users = await userService.GetAll()
            };
            var parentChildCategoreis = await this.categoryService.GetAllParentChildCategoriesForSelectingCategory();

            viewModel.ParentChildCategories = parentChildCategoreis.ParentChildCategories;

            if(searchbar == null && category==null)
            {
                viewModel.Courses = await courseService.GetAll();
            }
            else if(searchbar == null)
            {
                viewModel.Courses = await courseService.FilterByCategory(category);
            }
            else
            {
                viewModel.Courses = await courseService.FilterByTitle(searchbar);
            }

            return View(viewModel);
        }


        [HttpGet("Student/Courses/Details/{title}")]
        public async Task<IActionResult> Details([FromRoute] string title)
        {
            DetailsViewModel detailsViewModel = new DetailsViewModel()
            {
                Course = await courseService.GetCourse(title),
                Service = cloudinaryService,
                Username = User.Identity.Name
            };

            return View(detailsViewModel);
        }

        [HttpGet()]
        public async Task<IActionResult> MyCourses()
        {
            try
            {
                var user = await userService.GetByUsernameIncludeCourses(User.Identity.Name);
                var viewmodel = new MyCoursesViewModel()
                {
                    CurrentUser = user,
                    Service = cloudinaryService
                };

                return View(viewmodel);
            }
            catch(Exception e)
            {
                return NotFound(e.Message);
            }
        }

        [HttpPost]
        public async Task<IActionResult> EnrollForCourse(string courseTitle)
        {
            var viewModel = new DetailsViewModel()
            {
                Course = await courseService.GetCourse(courseTitle),
                Service = cloudinaryService,
                Username = User.Identity.Name
            };

            try
            {
                var result = await courseService.EnrollUserForCourse(viewModel.Username, courseTitle);
                viewModel.Course = result;
                return View("Details", viewModel);
            }
            catch (EntityNotFoundException e)
            {
                return View("Details", viewModel);
            }
        }

        [HttpGet("Student/Courses/EnrolledCourseView/{title}")]
        public async Task<IActionResult> EnrolledCourseView([FromRoute] string title)
        {
            var viewModel = new EnrolledCourseViewModel()
            {
                Course = await courseService.GetCourse(title),

                Username = User.Identity.Name
            };

            return View(viewModel);
        }

        [HttpGet]
        public async Task<JsonResult> GetCourses()
        {
            var result = await courseService.GetAll();

            string json = JsonConvert.SerializeObject(result, Formatting.Indented);

            return Json(json);
        }
    }
}

StudyJunction/StudyJunction.Web/Areas/Teacher/Controllers/CoursesController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authorization.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using StudyJunction.Core.ExternalApis;
using StudyJunction.Core.RequestDTOs.Course;
using StudyJunction.Core.Services.Contracts;
using StudyJunction.Core.ViewModels.Courses;
using StudyJunction.Infrastructure.Constants;
using StudyJunction.Infrastructure.Exceptions;

namespace StudyJunction.Web.Areas.Teacher.Controllers
{
    [Area(RolesConstants.Teacher)]
    [Authorize(Roles = RolesConstants.Teacher)]
    public class CoursesController : Controller
    {
        private readonly ICourseService courseService;
        private readonly IUserService userService;
        private readonly IMapper mapper;
        private readonly ICategoryService categoryService;
        private readonly CloudinaryService cloudinaryService;
        public CoursesController(ICourseService _courseService, IUserService _userService, IMapper _mapper, ICategoryService _categoryService,
            CloudinaryService _cloudinaryService)
        {
            courseService = _courseService;
            userService = _userService;
            mapper = _mapper;
            categoryService = _categoryService;
            cloudinaryService = _cloudinaryService;
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var viewModel = new CreateCourseViewModel();

            var parentChildCategoreis = await this.categoryService.GetAllParentChildCategoriesForSelectingCategory();

            viewModel.ParentChildCategories = parentChildCategoreis.ParentChildCategories;

            return View("Create", viewModel);
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateCourseViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            string username = HttpContext.Session.GetString("user");

            var course = mapper.Map<AddCourseRequestDto>(viewModel);

            _ = await courseService.Create(course, username);
            
            return RedirectToAction("GetCoursesCreatedByUser", "Courses", new {area = RolesConstants.Teacher});
        }

        [HttpGet]
        public async Task<IActionResult> Index(string searchValue)
        {
            CourseViewModel viewModel = new CourseViewModel()
            {
                Service = cloudinaryService,
                Users = await userService.GetAll()
            };
            if (searchValue != null)
            {
                viewModel.Courses = await courseService.FilterByTitle(searchValue);
            }
            else
            {
                viewModel.Courses = await courseService.GetAll();
            }

            return View(viewModel);
        }

        [HttpGet("Teacher/Courses/Details/{title}")]
        public async Task<IActionResult> Details([FromRoute] string title)
        {
            DetailsViewModel detailsViewModel = new DetailsViewModel()
            {
                Course = await courseService.GetCourse(title),
                Service = cloudinaryService,
                Username = User.Identity.Name
            };

            return View(detailsViewModel);
        }

        [HttpGet()]
        public async Task<IActionResult> MyCourses()
        {
            var user = await userService.GetByUsername(User.Identity.Name);
            var viewmodel = new MyCoursesViewModel()
            {
                CurrentUser = user,
                Service = cloudinaryService
            };

            return View(viewmodel);
        }

        [HttpGet]
        public async Task<IActionResult> GetCoursesCreatedByUser()
        {
            try
            {
			    string userId = HttpContext.Session.GetString("id");

                var models = await courseService.GetCoursesCreatedByUserAsync(userId);

                return View("CreatedByUserCourses", models);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", new { area = RolesConstants.Teacher });
			}
        }

        [HttpPost]
        public async Task<IActionResult> EnrollForCourse(string courseTitle)
        {
            var viewModel = new DetailsViewModel()
            {
                Course = await courseService.GetCourse(courseTitle),
                Service = cloudinaryService,
                Username = User.Identity.Name
            };

            try
            {
                var result = await courseService.EnrollUserForCourse(viewModel.Username, courseTitle);
                viewModel.Course = result;
                return View("Details", viewModel);
            }
            catch (EntityNotFoundException e)
            {
                return View("Details", viewModel);
            }
        }
    }
}

StudyJunction/StudyJunction.Web/Controllers/LecturesController.cs
using Microsoft.AspNetCore.Mvc;

namespace StudyJunction.Web.Controllers
{
    public class LecturesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

StudyJunction/StudyJunction.Web/Areas/Teacher/Views/Courses/Create.cshtml
@using StudyJunction.Core.ViewModels.Courses
@model CreateCourseViewModel

@{
    ViewData["Title"] = "Create course";
    // Layout = "~/Areas/Student/Views/Shared/_Layout.cshtml";
}

<section class="page-section" style="margin-left: 160px; margin-right: 160px; margin-top:30px;">

    <h2 style="margin-left:50px; margin-bottom:30px;">Create a New Course</h2>

    <form asp-area="Teacher" asp-controller="Courses" asp-action="Create" method="post" enctype="multipart/form-data" style="max-width: 600px; margin-left: 70px" id="postForm">

        <div class="form-group">
            <label asp-for="Title">Title</label>
            <input type="text" asp-for="Title" class="form-control" maxlength="50" id="titleInput" oninput="updateCounter('titleInput', 'titleCounter', 5, 50)" />
            <div style="margin-top:10px;" id="titleCounter" class="text-muted">Characters: 0/50</div>
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>

        <div class="form-group" style="margin-top: 25px">
            <label asp-for="Description">Description</label>
            <textarea asp-for="Description" class="form-control" style="width: 160%; height: 300px" maxlength="3000" id="contentInput" oninput="updateCounter('contentInput', 'contentCounter', 100, 3000)"></textarea>
            <div style="margin-top:10px;" id="contentCounter" class="text-muted">Characters: 0/3000</div>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>

        <div class="mb-3 form-group">
            <label asp-for="CategoryName" class="form-label">Category</label>
            <select asp-for="CategoryName" class="form-control">                    
                @foreach (var kvp in Model.ParentChildCategories)
                {
                    <optgroup label="@kvp.Key">
                        @foreach(var childCategories in kvp.Value)
                        {
                            <option value="@childCategories">@childCategories</option>
                        }
                    </optgroup>
                }
            </select>
        </div>

        <div>
            <input asp-for="Thumbnail" type="file" accept=".png" class="custom-file-input" id="customFile">
            <label asp-for="Thumbnail" class="custom-file-label" for="customFile">Choose Thumbnail in .png format</label>
        </div>

        <div class="form-group" style="margin-top: 25px">
            <button type="button" value="CourseCreation" class="btn btn-primary" onclick="validateAndSubmit()">Create Course</button>
        </div>


        <script>
            // Function to update character counters
            function updateCounter(inputId, counterId, minChars, maxChars) {
                const input = document.getElementById(inputId);
                const counter = document.getElementById(counterId);
                const currentChars = input.value.length;
                const remainingChars = maxChars - currentChars;

                counter.textContent = `Characters: ${currentChars}/${maxChars}`;

                // Change text color to red if the limit is exceeded or below the minimum length
                if (remainingChars <= 0 || currentChars < minChars) {
                    counter.style.color = 'red';
                } else {
                    counter.style.color = '';
                }
            }

            function validateAndSubmit() {
                // Check minimum length conditions
                const titleInput = document.getElementById('titleInput');
                const contentInput = document.getElementById('contentInput');

                if (titleInput.value.length < 5 || contentInput.value.length < 100) {
                    alert('Minimum length not reached. Please fill in all required fields.');
                    return;
                }

                // If conditions are met, submit the form
                document.getElementById('postForm').submit();
            }
        </script>
    </form>

</section>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

StudyJunction/StudyJunction.Web/Areas/Teacher/Views/Courses/CreatedByUserCourses.cshtml
@using StudyJunction.Core.ViewModels.Courses
@model List<CreatedCoursesViewModel>

<style>
	body {
		margin-top: 20px;
	}


	/* USER LIST TABLE */
	.user-list tbody td > img {
		position: relative;
		max-width: 50px;
		float: left;
		margin-right: 15px;
	}

	.user-list tbody td .user-link {
		display: block;
		font-size: 1.25em;
		padding-top: 3px;
		margin-left: 60px;
	}

	.user-list tbody td .user-subhead {
		font-size: 0.875em;
		font-style: italic;
	}

	/* TABLES */
	.table {
		border-collapse: separate;
	}

	.table-hover > tbody > tr:hover > td,
	.table-hover > tbody > tr:hover > th {
		background-color: #eee;
	}

	.table thead > tr > th {
		border-bottom: 1px solid #C2C2C2;
		padding-bottom: 0;
	}

	.table tbody > tr > td {
		font-size: 0.875em;
		background: #f5f5f5;
		border-top: 10px solid #fff;
		vertical-align: middle;
		padding: 12px 8px;
	}

		.table tbody > tr > td:first-child,
		.table thead > tr > th:first-child {
			padding-left: 20px;
		}

	.table thead > tr > th span {
		border-bottom: 2px solid #C2C2C2;
		display: inline-block;
		padding: 0 5px;
		padding-bottom: 5px;
		font-weight: normal;
	}

	.table thead > tr > th > a span {
		color: #344644;
	}

		.table thead > tr > th > a span:after {
			content: "\f0dc";
			font-family: FontAwesome;
			font-style: normal;
			font-weight: normal;
			text-decoration: inherit;
			margin-left: 5px;
			font-size: 0.75em;
		}

	.table thead > tr > th > a.asc span:after {
		content: "\f0dd";
	}

	.table thead > tr > th > a.desc span:after {
		content: "\f0de";
	}

	.table thead > tr > th > a:hover span {
		text-decoration: none;
		color: #2bb6a3;
		border-color: #2bb6a3;
	}

	.table.table-hover tbody > tr > td {
		-webkit-transition: background-color 0.15s ease-in-out 0s;
		transition: background-color 0.15s ease-in-out 0s;
	}

	.table tbody tr td .call-type {
		display: block;
		font-size: 0.75em;
		text-align: center;
	}

	.table tbody tr td .first-line {
		line-height: 1.5;
		font-weight: 400;
		font-size: 1.125em;
	}

		.table tbody tr td .first-line span {
			font-size: 0.875em;
			color: #969696;
			font-weight: 300;
		}

	.table tbody tr td .second-line {
		font-size: 0.875em;
		line-height: 1.2;
	}

	.table a.table-link {
		margin: 0 5px;
		font-size: 1.125em;
	}

		.table a.table-link:hover {
			text-decoration: none;
			color: #2aa493;
		}

		.table a.table-link.danger {
			color: #fe635f;
		}

			.table a.table-link.danger:hover {
				color: #dd504c;
			}

	.table-products tbody > tr > td {
		background: none;
		border: none;
		border-bottom: 1px solid #ebebeb;
		-webkit-transition: background-color 0.15s ease-in-out 0s;
		transition: background-color 0.15s ease-in-out 0s;
		position: relative;
	}

	.table-products tbody > tr:hover > td {
		text-decoration: none;
		background-color: #f6f6f6;
	}

	.table-products .name {
		display: block;
		font-weight: 600;
		padding-bottom: 7px;
	}

	.table-products .price {
		display: block;
		text-decoration: none;
		width: 50%;
		float: left;
		font-size: 0.875em;
	}

		.table-products .price > i {
			color: #8dc859;
		}

	.table-products .warranty {
		display: block;
		text-decoration: none;
		width: 50%;
		float: left;
		font-size: 0.875em;
	}

		.table-products .warranty > i {
			color: #f1c40f;
		}

	.table tbody > tr.table-line-fb > td {
		background-color: #9daccb;
		color: #262525;
	}

	.table tbody > tr.table-line-twitter > td {
		background-color: #9fccff;
		color: #262525;
	}

	.table tbody > tr.table-line-plus > td {
		background-color: #eea59c;
		color: #262525;
	}

	.table-stats .status-social-icon {
		font-size: 1.9em;
		vertical-align: bottom;
	}

	.table-stats .table-line-fb .status-social-icon {
		color: #556484;
	}

	.table-stats .table-line-twitter .status-social-icon {
		color: #5885b8;
	}

	.table-stats .table-line-plus .status-social-icon {
		color: #a75d54;
	}
</style>

<div class="table-responsive">
	<table class="table user-list">
		<thead>
			<tr>
				<th><span>Course Title</span></th>
				<th><span>Number Of Lectures</span></th>
				<th><span>Enrolled Students</span></th>
				<th><span>Is Approved</span></th>
				<th><span>Action</span></th>
			</tr>
		</thead>
		<tbody>
			@foreach (var course in Model)
			{
				<tr>
					<td>
						<div>@course.Title</div>
					</td>
					<td>
						<div>@course.NumberOfLectures</div>
					</td>
					<td>
						<div>@course.NumberOfEnrolledStudents</div>
					</td>
					<td>
						@if (course.IsApproved)
						{
							<div>Approved</div>
						}
						else
						{
							<div>Not Approved</div>
						}
					</td>
					<td>
						@using (Html.BeginForm("Add", "Lectures", FormMethod.Get, new { area = "Teacher" }))
						{
							<!-- Other form elements -->
							@Html.Hidden("courseTitle", course.Title)

							<input type="submit" value="Add Lecture" />
						}
					</td>
				</tr>
			}
		</tbody>
	</table>
</div>

StudyJunction/StudyJunction.Web/Areas/Teacher/Views/Courses/Index.cshtml
@using StudyJunction.Core.ViewModels.Courses
@using StudyJunction.Core.ResponseDTOs
@using CloudinaryDotNet
@using CloudinaryDotNet.Actions

@model CourseViewModel

@{
    ViewData["Title"] = "List of courses";
}

<!-- ======= Breadcrumbs ======= -->
<div class="align-self-center justify-content-center align-items-center">
    <div class="breadcrumbs" style="margin-top: 0; padding: 5px;">
        <div class="container">
            <h2>Courses</h2>
            <p>
                Choose amongst all our available courses.
                Use the search bar for quick access and filter them by categories.
            </p>
        </div>
    </div><!-- End Breadcrumbs -->
</div>


<!-- Search bar -->
<div class="col-2 m-4">
    @using (Html.BeginForm("Index", "Courses", FormMethod.Get, new { @class = "d-flex" }))
    {
        @Html.TextBox("searchValue", null, new { Class = "form-control", placeholder = "Search courses" })
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    }
    @* <form class="d-flex my-2">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> *@
</div>



<!-- ======= Courses Section ======= -->
@if (Model.Courses.Count() != 0)
{
    <section id="courses" class="courses m-3" style="padding: 0;">
        <div data-aos="fade-up">
            @for (int i = 0; i < Model.Courses.Count(); i += 3)
            {
                <div class="row" data-aos="zoom-in" data-aos-delay="100">
                    @for (int j = i; j < i + 3; j++)
                    {
                        @if (j >= Model.Courses.Count())
                        {
                            break;
                        }
                        var currCourse = Model.Courses.ElementAt(j);
                        var creator = Model.Users.FirstOrDefault(u => u.UserName == currCourse.CreatorName);

                        <div class="col-lg-4 col-md-6 d-flex align-items-stretch">
                            <div class="course-item">
                                @{
                                    string[] splitted = currCourse.Title.Split();
                                    string url = "http://localhost:5205/Teacher/Courses/Details/" + String.Join("%20", splitted);
                                }
                                <a href=@url>
                                    <img src="@Model.Service.GetResource(currCourse.ThumbnailCloudinaryUri)" class="img-fluid" width="500" height="1100" alt="Course thumbnail">
                                </a>

                                <div class="course-content">
                                    <div class="d-flex justify-content-between align-items-center mb-3">
                                        <h4>@currCourse.CategoryName</h4>
                                        <p class="price">$169</p>
                                    </div>

                                    <h3><a href=@url>@currCourse.Title</a></h3>
                                    <p>@currCourse.Description</p>
                                    <div class="trainer d-flex justify-content-between align-items-center">
                                        <div class="trainer-profile d-flex align-items-center">
                                            <img src="@Model.Service.GetResource(creator.ProfileImageCloudinaryUri)" class="img-fluid" alt="">
                                            <span>@creator.FirstName @creator.LastName</span>
                                        </div>
                                        <div class="trainer-rank d-flex align-items-center">
                                            <i class="bx bx-user"></i>&nbsp;50
                                            &nbsp;&nbsp;
                                            <i class="bx bx-heart"></i>&nbsp;65
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div> <!-- End Course Item-->
                    }
                </div> <!-- End row -->
            }
        </div>
    </section>

    <!-- End Courses Section -->
}
else
{
    <h3 style="margin-left: 1.5rem">No courses found.</h3>
}


<!-- Vendor JS Files -->
<script src="~/assets/vendor/purecounter/purecounter_vanilla.js"></script>
<script src="~/assets/vendor/aos/aos.js"></script>
<script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/assets/vendor/swiper/swiper-bundle.min.js"></script>
<script src="~/assets/vendor/php-email-form/validate.js"></script>

<!-- Template Main JS File -->
<script src="~/assets/js/main.js"></script>

StudyJunction/StudyJunction.Web/Areas/Teacher/Views/Courses/MyCourses.cshtml
@using StudyJunction.Core.ViewModels.Courses
@using StudyJunction.Core.ResponseDTOs
@using CloudinaryDotNet
@using CloudinaryDotNet.Actions

@model MyCoursesViewModel

@{
    ViewData["Title"] = "List enrolled courses";
}



<link href="~/css/MyCoursesPageStyle.css" rel="stylesheet">



<div class="header bg-dark text-light">
    <div class="header-inner">
        <h1 class="mb-0">My Learning</h1>
    </div>

    <nav>
        <div class="container">
            <ul class="nav justify-content-center">
                <li class="nav-item">
                    <button class="section-select" type="button">My Learning</button>
                </li>
                <li class="nav-item">
                    <button class="section-select" type="button">My Created Courses</button>
                </li>
            </ul>
        </div>
    </nav>
</div>


@{
    var userCourses = Model.CurrentUser.MyEnrolledCourses;
}

<div class="container mt-4">
    @for (int r = 0; r < userCourses.Count; r += 3)
    {
        //open row
        <div class="row">
            @for (int c = r; c < r + 3; c++)
            {
                @if (c >= userCourses.Count)
                {
                    break;
                }

                var currCourse = userCourses.ElementAt(c);

                <div class="col-md-4 mb-4">
                    <div class="card">
                        <div class="card-body">
                            <img src="@Model.Service.GetResource(currCourse.ThumbnailCloudinaryUri)" class="img-fluid" alt="Course thumbnail">
                            <h5 class="card-title">@currCourse.Title</h5>
                            <p class="card-text">@currCourse.Description</p>
                        </div>
                    </div>
                </div>
            }
        </div>

    }
</div>