StudyJunction/StudyJunction.Web/Areas/Teacher/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StudyJunction.Infrastructure.Constants;

namespace StudyJunction.Web.Areas.Teacher.Controllers
{
    [Area(RolesConstants.Teacher)]
    [Authorize(Roles = RolesConstants.Teacher)]
    public class UsersController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

StudyJunction/StudyJunction.Web/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Mvc;

namespace StudyJunction.Web.Controllers
{
    public class CategoriesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

StudyJunction/StudyJunction.Web/Areas/Admin/Views/Shared/_AdminLayout.cshtml
@using Microsoft.AspNetCore.Identity
@using StudyJunction.Infrastructure.Data.Models
@inject SignInManager<UserDb> SignInManager
@inject UserManager<UserDb> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>

    <title>StudyJunction - Index</title>
    <meta content="" name="description"/>
    <meta content="" name="keywords"/>

    <!-- Favicons -->
    <link href="~/assets/img/favicon.png" rel="icon"/>
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon"/>
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet"/>

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/animate.css/animate.min.css" rel="stylesheet"/>
    <link href="~/assets/vendor/aos/aos.css" rel="stylesheet"/>
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet"/>
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet"/>
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet"/>
    <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet"/>
    <link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet"/>

    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet"/>

    <!-- =======================================================
    * Template Name: Mentor
    * Updated: Jan 29 2024 with Bootstrap v5.3.2
    * Template URL: https://bootstrapmade.com/mentor-free-education-bootstrap-theme/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top" style="position: relative;">
        <div class="container d-flex align-items-center">
            <img src="~/assets/img/aerondight___green-themed_logo_with_asphalt_roads_crossing_eac_012d7662-32da-4083-92bc-e4686cb979d8.png" width="100px" height="100px" class="img-fluid" alt="Logo" />
            <h1 class="logo me-auto"><a>StudyJunction</a></h1>
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <a href="index.html" class="logo me-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

            <nav id="navbar" class="navbar order-last order-lg-0">
                <ul>
                    @* <li><a class="active" href="http://localhost:5205/Home/Index">Home</a></li>
                    <li><a href="about.html">About</a></li>
                    <li><a asp-controller="Courses" asp-action="Create" asp-area="Student">Courses</a></li> *@
                    <li><a asp-area="Admin" asp-controller="Users" asp-action="UsersRoles">UsersRoles</a></li>
                    <li><a asp-area="Admin" asp-controller="TeacherCandidacy" asp-action="GetAll">Review Teacher Candidacies</a></li>
                    <li><a asp-area="Admin" asp-controller="Courses" asp-action="GetAllForApproval">Courses for Approval</a></li>
                    <li><a asp-area="Admin" asp-controller="Categories" asp-action="Add">Add Category</a></li>
                    
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->

            @if (SignInManager.IsSignedIn(User))
            {                
                <a class="get-started-btn" asp-controller="Users" asp-action="" title="Manage">Hello @User.Identity?.Name!</a>

                <form class="form-inline" >
                    <button class="nav-link btn btn-link text-dark" asp-controller="Users" asp-action="Logout" asp-area="Student" type="submit">Logout2</button>
                </form>                
            }
            else
            {                
                <a class="get-started-btn" asp-controller="Users" asp-action="Register">Register</a>
                               
                <a class="get-started-btn" asp-controller="Users" asp-action="Login">Login</a>                
            }
        </div>
    </header><!-- End Header -->
    <div @*style="margin-top: 150px"*@>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- ======= Footer ======= -->
    <footer id="footer">

        <div class="footer-top">
            <div class="container">
                <div class="row">

                    <div class="col-lg-3 col-md-6 footer-contact">
                        <h3>StudyJunction</h3>
                        <p>
                            A108 Adam Street <br>
                            New York, NY 535022<br>
                            United States <br><br>
                            <strong>Phone:</strong> +1 5589 55488 55<br>
                            <strong>Email:</strong> info@example.com<br>
                        </p>
                    </div>

                    <div class="col-lg-2 col-md-6 footer-links">
                        <h4>Useful Links</h4>
                        <ul>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-md-6 footer-links">
                        <h4>Our Services</h4>
                        <ul>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-4 col-md-6 footer-newsletter">
                        <h4>Join Our Newsletter</h4>
                        <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
                        <form action="" method="post">
                            <input type="email" name="email"><input type="submit" value="Subscribe">
                        </form>
                    </div>

                </div>
            </div>
        </div>

        <div class="container d-md-flex py-4">

            <div class="me-md-auto text-center text-md-start">
                <div class="copyright">
                    &copy; Copyright <strong><span>StudyJunction</span></strong>. All Rights Reserved
                </div>
                <div class="credits">
                    <!-- All the links in the footer should remain intact. -->
                    <!-- You can delete the links only if you purchased the pro version. -->
                    <!-- Licensing information: https://bootstrapmade.com/license/ -->
                    <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/mentor-free-education-bootstrap-theme/ -->
                    Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
                </div>
            </div>
            <div class="social-links text-center text-md-right pt-3 pt-md-0">
                <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
            </div>
        </div>
    </footer><!-- End Footer -->

@*     <div id="loader"></div> 
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center">A<i class="bi bi-arrow-up-short"></i></a> *@

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

@* <script>

    $(document).ready(function () {
        $("#loader").hide();
    }
</script> *@